const Room = require('../models/Room');

// In-memory room state
const lockedRooms = new Set();
const roomUsers = new Map(); // roomId -> Map(socketId -> userObj)

const sanitizeRoomId = (raw) => {
  if (!raw) return '';
  let str = String(raw).trim();
  if (str.includes('room=')) {
    try {
      const urlPart = str.includes('?') ? str.split('?')[1] : str;
      const params = new URLSearchParams(urlPart);
      const r = params.get('room');
      if (r) return r.trim();
    } catch (e) {}
  }
  return str.replace(/^https?:\/\/[^/]+\/?/i, '').replace(/[^a-zA-Z0-9_-]/g, '').trim() || str.trim();
};

const syncHandler = (io, socket) => {
  console.log('⚡ User Connected:', socket.id);

  // ── Room Join ──
  socket.on('join-room', ({ roomId: rawRoomId, userId, userName, userRole }) => {
    const roomId = sanitizeRoomId(rawRoomId);
    // Check if room is locked
    if (lockedRooms.has(roomId) && userRole !== 'instructor') {
      socket.emit('room-locked-error', { message: 'This room has been locked by the instructor.' });
      return;
    }

    socket.join(roomId);
    socket.roomId = roomId;
    const altRoom = roomId.replace(/-/g, '');
    if (altRoom && altRoom !== roomId) {
      socket.join(altRoom);
    }

    if (!roomUsers.has(roomId)) {
      roomUsers.set(roomId, new Map());
    }
    const currentRoomMap = roomUsers.get(roomId);
    currentRoomMap.set(socket.id, {
      socketId: socket.id,
      userId: userId || socket.id,
      userName: userName || (userRole === 'instructor' ? 'Instructor' : `Student #${socket.id.substring(0,4)}`),
      userRole: userRole || 'student'
    });

    console.log(`👤 User ${userId || socket.id} (${userName || userRole}) joined Room: ${roomId}`);
    
    // Persist Room and Session Participants directly to MongoDB
    (async () => {
      try {
        const updateDoc = {
          isActive: true,
          studentsCount: currentRoomMap.size,
          participants: Array.from(currentRoomMap.values()).map(u => ({
            socketId: u.socketId,
            userName: u.userName,
            userRole: u.userRole,
            joinedAt: new Date()
          }))
        };
        if (userRole === 'instructor') {
          updateDoc.instructorName = userName || 'Instructor';
        }
        await Room.findOneAndUpdate(
          { roomId },
          {
            $set: updateDoc,
            $setOnInsert: { title: `Live Classroom (${roomId})` }
          },
          { upsert: true, new: true }
        );
        console.log(`💾 Persisted room "${roomId}" to MongoDB (synclearn_app.rooms)`);

        // Also ensure user exists in synclearn_app.users
        const User = require('../models/User');
        const effectiveName = (userName || (userRole === 'instructor' ? 'Instructor' : 'Student')).trim();
        const safeName = effectiveName.toLowerCase().replace(/[^a-z0-9]/g, '');
        const autoEmail = `${safeName || 'user'}@student.synclearn.edu`;

        await User.findOneAndUpdate(
          { name: effectiveName },
          {
            $set: {
              name: effectiveName,
              role: userRole || 'student',
              lastLogin: new Date()
            },
            $setOnInsert: {
              email: autoEmail,
              password: '$2b$10$autogeneratedStudentPasswordPlaceholder'
            }
          },
          { upsert: true, new: true }
        );
        console.log(`💾 Persisted user "${effectiveName}" to MongoDB (synclearn_app.users)`);
      } catch (err) {
        console.warn('MongoDB room/user persist error:', err.message);
      }
    })();

    // Notify peers for WebRTC
    socket.to(roomId).emit('user-connected', userId || socket.id);

    // Broadcast updated participant roster
    io.to(roomId).emit('room-participants-update', Array.from(currentRoomMap.values()));
    socket.emit('room-lock-status', { isLocked: lockedRooms.has(roomId) });

    // Broadcast user joined toast notification to all peers in the room
    socket.to(roomId).emit('peer-joined-notification', {
      userName: userName || (userRole === 'instructor' ? 'Instructor' : 'A student'),
      userRole: userRole || 'student',
      totalCount: currentRoomMap.size
    });
  });

  // ── Host Controls: Mute All ──
  socket.on('host-mute-all', ({ roomId }) => {
    console.log(`🔇 Host muted all in room: ${roomId}`);
    socket.to(roomId).emit('force-mute');
  });

  // ── Host Controls: Individual Student Mute ──
  socket.on('host-mute-student', ({ roomId, targetSocketId }) => {
    console.log(`🔇 Host muted student ${targetSocketId} in ${roomId}`);
    io.to(targetSocketId).emit('force-mute', { byHost: true });
  });

  // ── Host Controls: Individual Student Camera Toggle ──
  socket.on('host-toggle-student-camera', ({ roomId, targetSocketId, action }) => {
    console.log(`📹 Host requested camera ${action} for student ${targetSocketId} in ${roomId}`);
    io.to(targetSocketId).emit('force-toggle-camera', { action });
  });

  // ── Participant Media State Update Broadcast ──
  socket.on('media-state-change', ({ roomId, videoOn, micOn }) => {
    socket.to(roomId).emit('peer-media-state-change', {
      socketId: socket.id,
      videoOn,
      micOn
    });
  });

  // ── Host Controls: Lock / Unlock Room ──
  socket.on('host-toggle-lock', ({ roomId, isLocked }) => {
    if (isLocked) {
      lockedRooms.add(roomId);
    } else {
      lockedRooms.delete(roomId);
    }
    console.log(`🔒 Room ${roomId} lock status: ${isLocked}`);
    io.to(roomId).emit('room-lock-status', { isLocked });
  });

  // ── Host Controls: Remove Participant ──
  socket.on('host-remove-peer', ({ roomId, targetSocketId }) => {
    console.log(`🚫 Host removed participant ${targetSocketId} from ${roomId}`);
    io.to(targetSocketId).emit('force-removed', { reason: 'You have been removed from the session by the host.' });
  });

  // ── Live Lecture Transcription Broadcast ──
  socket.on('new-transcription', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    if (targetRoom) {
      socket.to(targetRoom).emit('receive-transcription', data);
    }
  });

  // ── Real-Time Live YouTube-Style Captions / Subtitles Stream ──
  socket.on('live-caption-stream', (data) => {
    const rawTarget = data?.roomId || socket.roomId;
    const targetRoom = sanitizeRoomId(rawTarget);
    if (targetRoom && data?.text) {
      const payload = {
        speaker: data.speaker || 'Instructor',
        role: data.role || 'instructor',
        text: data.text,
        isFinal: !!data.isFinal,
        timestamp: data.timestamp || Date.now()
      };
      console.log(`🎙️ [Live Caption] Room: ${targetRoom} | ${payload.speaker}: "${payload.text}"`);
      socket.to(targetRoom).emit('receive-live-caption', payload);
      const altRoom = targetRoom.replace(/-/g, '');
      if (altRoom && altRoom !== targetRoom) {
        socket.to(altRoom).emit('receive-live-caption', payload);
      }
    }
  });

  // ── Clear Live Caption (when speaker stops) ──
  socket.on('clear-live-caption', (data) => {
    const rawTarget = data?.roomId || socket.roomId;
    const targetRoom = sanitizeRoomId(rawTarget);
    if (targetRoom) {
      socket.to(targetRoom).emit('receive-clear-caption');
      const altRoom = targetRoom.replace(/-/g, '');
      if (altRoom && altRoom !== targetRoom) {
        socket.to(altRoom).emit('receive-clear-caption');
      }
    }
  });

  // ── Live Chat ──
  socket.on('send-message', (data) => {
    io.to(data.roomId).emit('receive-message', {
      id: data.id || ('msg_' + Date.now() + '_' + Math.random().toString(36).substr(2, 4)),
      message: data.message,
      senderId: data.senderId,
      senderName: data.senderName,
      senderRole: data.senderRole || 'student',
      isDoubt: !!data.isDoubt,
      file: data.file || null,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    });
  });

  // ── Pinned Doubts System ──
  socket.on('pin-doubt', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    console.log(`📌 [pin-doubt] Received in room "${targetRoom}":`, data?.doubt?.text);
    if (targetRoom) {
      io.to(targetRoom).emit('doubt-pinned', data.doubt);
      const altRoom = targetRoom.replace(/-/g, '');
      if (altRoom && altRoom !== targetRoom) {
        io.to(altRoom).emit('doubt-pinned', data.doubt);
      }
    }
    // Also emit back to the sender directly to guarantee instant confirmation
    socket.emit('doubt-pinned', data.doubt);
  });

  socket.on('resolve-doubt', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    console.log(`✅ [resolve-doubt] Received in room "${targetRoom}" for doubt:`, data?.doubtId);
    if (targetRoom) {
      io.to(targetRoom).emit('doubt-resolved', { doubtId: data.doubtId });
      const altRoom = targetRoom.replace(/-/g, '');
      if (altRoom && altRoom !== targetRoom) {
        io.to(altRoom).emit('doubt-resolved', { doubtId: data.doubtId });
      }
    }
    socket.emit('doubt-resolved', { doubtId: data.doubtId });
  });

  socket.on('seek-to-video-time', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    io.to(targetRoom).emit('seek-to-video-time', data);
    const altRoom = targetRoom.replace(/-/g, '');
    if (altRoom && altRoom !== targetRoom) {
      io.to(altRoom).emit('seek-to-video-time', data);
    }
  });

  // ── AI Lecture Quiz Sync & Leaderboard ──
  socket.on('publish-quiz', (data) => {
    io.to(data.roomId).emit('room-quiz-published', data.quiz);
  });

  socket.on('submit-quiz-score', (data) => {
    io.to(data.roomId).emit('student-score-submitted', {
      studentId: socket.id,
      studentName: data.studentName,
      score: data.score,
      total: data.total,
      percentage: Math.round((data.score / data.total) * 100),
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    });
  });

  // ── Student Attention & Engagement Telemetry ──
  socket.on('student-engagement-update', (data) => {
    socket.to(data.roomId).emit('peer-engagement-stat', {
      socketId: socket.id,
      studentName: data.studentName,
      score: data.score,
      isFocused: data.isFocused,
    });
  });

  // ── Hand Raise Queue ──
  socket.on('raise-hand', (data) => {
    io.to(data.roomId).emit('student-hand-raised', {
      socketId: socket.id,
      studentName: data.studentName,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    });
  });

  socket.on('lower-hand', (data) => {
    io.to(data.roomId).emit('student-hand-lowered', {
      socketId: data.socketId || socket.id,
    });
  });

  // ── Category 3: Breakout Rooms / Discussion Pods ──
  socket.on('breakout-create', (data) => {
    // Broadcast newly created pod announcement
    io.to(data.roomId).emit('breakout-created', {
      podId: data.podId || (`pod_${Date.now()}`),
      podName: data.podName,
      createdByName: data.createdByName,
      roomId: data.roomId,
      membersCount: 0
    });
  });

  socket.on('breakout-close', (data) => {
    io.to(data.roomId).emit('breakout-closed', { podId: data.podId });
  });

  // ── Category 3: Session Recording Broadcast ──
  socket.on('recording-status-change', (data) => {
    socket.to(data.roomId).emit('recording-status-change', {
      isRecording: data.isRecording,
      recordedByName: data.recordedByName
    });
  });

  // ── Whiteboard: Pen / Eraser strokes ──
  socket.on('draw-stroke', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('draw-stroke', data);
  });

  // ── Whiteboard: Shape tools (line / rect) ──
  socket.on('draw-shape', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('draw-shape', data);
  });

  // ── Whiteboard: Clear canvas ──
  socket.on('clear-canvas', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('clear-canvas');
  });

  // ── Whiteboard: Laser Pointer Sync ──
  socket.on('whiteboard-laser', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('whiteboard-laser', data);
  });

  // ── Whiteboard: Undo / Redo Snapshot Restore ──
  socket.on('whiteboard-restore-snapshot', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('whiteboard-restore-snapshot', data);
  });

  // ── Whiteboard: Live Typed Notes Sync ──
  socket.on('whiteboard-typing-sync', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('whiteboard-typing-sync', data);
  });

  // ── Whiteboard: Initial Canvas Sync for newly joined students ──
  socket.on('request-canvas-state', (data) => {
    const targetRoom = sanitizeRoomId(data?.roomId) || socket.roomId;
    socket.to(targetRoom).emit('send-canvas-state', { targetSocketId: socket.id });
  });

  socket.on('canvas-state-response', (data) => {
    if (data?.targetSocketId) {
      io.to(data.targetSocketId).emit('whiteboard-restore-snapshot', {
        snapshot: data.snapshot,
        notes: data.notes,
        fontSize: data.fontSize,
        textColor: data.textColor
      });
    }
  });

  // ── Synchronized Video Player & YouTube Collaboration ──
  socket.on('video-state-change', (data) => {
    socket.to(data.roomId).emit('video-state-change', data);
  });

  socket.on('video-source-change', (data) => {
    socket.to(data.roomId).emit('video-source-change', data);
  });

  // ── 3D Model Viewer Sync (Rotation + Zoom) ──
  socket.on('model-rotate', (data) => {
    socket.to(data.roomId).emit('model-rotate', data);
  });

  // ── Timeline Annotation Pins ──
  socket.on('pin-annotation', (data) => {
    socket.to(data.roomId).emit('pin-annotation', data);
  });

  // ── WebRTC Signaling ──
  socket.on('sending-signal', (payload) => {
    io.to(payload.userToSignal).emit('user-joined', {
      signal: payload.signal,
      callerID: payload.callerID,
    });
  });

  socket.on('returning-signal', (payload) => {
    io.to(payload.callerID).emit('receiving-returned-signal', {
      signal: payload.signal,
      id: socket.id,
    });
  });

  // ── Disconnect: notify room peers and update roster ──
  socket.on('disconnect', () => {
    console.log('❌ User Disconnected:', socket.id);
    if (socket.roomId) {
      socket.to(socket.roomId).emit('user-disconnected', socket.id);

      if (roomUsers.has(socket.roomId)) {
        const currentRoomMap = roomUsers.get(socket.roomId);
        currentRoomMap.delete(socket.id);
        const remainingCount = currentRoomMap.size;

        if (remainingCount === 0) {
          roomUsers.delete(socket.roomId);
          lockedRooms.delete(socket.roomId);
        } else {
          io.to(socket.roomId).emit('room-participants-update', Array.from(currentRoomMap.values()));
        }

        // Update MongoDB document
        Room.findOneAndUpdate(
          { roomId: socket.roomId },
          {
            $set: {
              studentsCount: remainingCount,
              isActive: remainingCount > 0,
              ...(remainingCount === 0 ? { endedAt: new Date() } : {})
            },
            $pull: { participants: { socketId: socket.id } }
          }
        ).catch(() => {});
      }
    }
  });
};

module.exports = syncHandler;
